// Generated by CoffeeScript 1.10.0
(function() {
  var active, code, string, target;

  $(document).ready(function() {
    $('.stars').each(function() {
      var results, stars;
      stars = $(this).data('stars');
      results = [];
      while (stars -= 1) {
        results.push($(this).append('<i class="fa fa-star">'));
      }
      return results;
    });
    return $('.fancybox').fancybox({
      helpers: {
        overlay: {
          locked: false
        }
      }
    });
  });

  if (window.location.hash !== '') {
    target = $(window.location.hash);
  }

  $('.scroll').smoothScroll().click(function(e) {
    return target = $(e.target.hash);
  });

  active = false;

  string = '';

  code = '7848486683';

  $(window).on({
    'keydown': function(e) {
      var keycode;
      keycode = e.keyCode;
      string += keycode;
      if (string.length === 10) {
        if (string === code) {
          $('#flash').slideDown();
          setTimeout(function() {
            return $('#flash').slideUp();
          }, 3000);
          string = '';
        } else {
          string = '';
        }
      }
      if (keycode === 40 || keycode === 38) {
        e.preventDefault();
        e.stopPropagation();
        if (active) {
          return;
        }
        if (keycode === 38) {
          if (target === void 0) {
            target = $('.page');
          } else if (!$(target.prev()).is('#sidebar')) {
            target = target.prev();
          }
        } else if (keycode === 40) {
          if (target === void 0) {
            target = $('.page').next();
          } else if ($(target.next()).hasClass('page')) {
            target = target.next();
          }
        }
        active = true;
        setTimeout(function() {
          return active = false;
        }, 500);
        return $('html, body').animate({
          scrollTop: $(target).offset().top
        }, 600);
      }
    },
    'mousewheel DOMMouseScroll': function(e) {
      var delta;
      e.preventDefault();
      e.stopPropagation();
      if (active) {
        return;
      }
      delta = 0;
      if (navigator.userAgent.toLowerCase().indexOf('firefox') > -1) {
        console.log('Firefox');
        delta = e.originalEvent.detail > 0 ? -1 : 1;
      } else {
        console.log('Other');
        delta = e.originalEvent.wheelDelta;
      }
      active = true;
      setTimeout(function() {
        return active = false;
      }, 500);
      console.log('Delta: ' + delta);
      if (delta > 0) {
        if (target === void 0) {
          target = $('.page');
        } else {
          if (!$(target.prev()).is('#sidebar')) {
            target = target.prev();
          }
        }
      } else {
        if (target === void 0) {
          target = $('.page').next();
        } else {
          if ($(target.next()).hasClass('page')) {
            target = target.next();
          }
        }
      }
      return $('html, body').animate({
        scrollTop: $(target).offset().top
      }, 600);
    }
  });

  setInterval(function() {
    if (target === void 0 || target.is('#home')) {
      $('#sidebar').fadeOut();
      return $('#header').fadeOut();
    } else {
      $('#sidebar').fadeIn();
      return $('#header').fadeIn();
    }
  });


  /* Mobile */

  $('#mobileSidebarButton').click(function() {
    var mobileSidebar;
    mobileSidebar = $('#mobileSidebar');
    if (mobileSidebar.hasClass('active')) {
      mobileSidebar.animate({
        width: 0
      }, 200, function() {
        return mobileSidebar.css({
          display: 'none',
          overflow: 'hidden'
        });
      });
      return mobileSidebar.removeClass('active');
    } else {
      mobileSidebar.css({
        display: 'block'
      }.animate({
        width: '100%'
      }, 200));
      return mobileSidebar.addClass('active');
    }
  });

  $('#mobileSidebar a').click(function() {
    var mobileSidebar;
    mobileSidebar = $('#mobileSidebar');
    mobileSidebar.removeClass('active');
    return mobileSidebar.animate({
      width: 0
    }, 200, function() {
      return mobileSidebar.css({
        display: 'none',
        overflow: 'hidden'
      });
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
